# Import necessary modules
rule all:
    input:
        "CoNECo-corpus.tar.gz",
        "CoNECo_train-ids-with-dirs.txt",
        "CoNECo_dev-ids-with-dirs.txt",
        "CoNECo_test-ids-with-dirs.txt"


rule generate_train_dev_test_lists:
    input:
        "data_split_CoNECo_dirs.tsv"
    output:
        "CoNECo_train-ids-with-dirs.txt",
        "CoNECo_dev-ids-with-dirs.txt",
        "CoNECo_test-ids-with-dirs.txt"
    params:
        temp_file_prefix=""
    shell:
        """
        awk -F"\t" '{{if($3==1){{printf("%s\t%s\n",$1, $2) >> "CoNECo_train-ids-with-dirs.txt"}}}{{if($4==1){{printf("%s\t%s\n",$1, $2) >> "CoNECo_dev-ids-with-dirs.txt"}}}{{if($5==1){{printf("%s\t%s\n",$1, $2) >> "CoNECo_test-ids-with-dirs.txt"}}}}' data_split_CoNECo_dirs.tsv
        """



values = ["complex-formation-batch-01", "complex-formation-batch-02", "genetic-interaction-dbs-abstracts-01", "physical-interaction-dbs-abstracts-01", "physical-interaction-dbs-abstracts-02", "physical-interaction-dbs-full-texts-01", "physical-interaction-dbs-full-texts-02", "regulatory-interactions-reactome-abstracts-01", "ptm-triaged-abstracts-01", "exhaustive-ptm-corpus-for-re"]

rule download_files:
    output:
        expand("{collection}.tar.gz", collection=values)
    
    shell:
        """
        wget 'http://ann.turkunlp.org:8088/ajax.cgi?action=downloadCollection&collection=%2Fstring-relation-corpus%2Fcomplex-formation-batch-01%2F&include_conf=1&protocol=1' -O complex-formation-batch-01.tar.gz
        wget 'http://ann.turkunlp.org:8088/ajax.cgi?action=downloadCollection&collection=%2Fstring-relation-corpus%2Fcomplex-formation-batch-02%2F&include_conf=1&protocol=1' -O complex-formation-batch-02.tar.gz
        wget 'http://ann.turkunlp.org:8088/ajax.cgi?action=downloadCollection&collection=%2Fstring-relation-corpus%2Fgenetic-interaction-dbs-abstracts-01%2F&include_conf=1&protocol=1' -O genetic-interaction-dbs-abstracts-01.tar.gz
        wget 'http://ann.turkunlp.org:8088/ajax.cgi?action=downloadCollection&collection=%2Fstring-relation-corpus%2Fphysical-interaction-dbs-abstracts-01%2F&include_conf=1&protocol=1' -O physical-interaction-dbs-abstracts-01.tar.gz
        wget 'http://ann.turkunlp.org:8088/ajax.cgi?action=downloadCollection&collection=%2Fstring-relation-corpus%2Fphysical-interaction-dbs-abstracts-02%2F&include_conf=1&protocol=1' -O physical-interaction-dbs-abstracts-02.tar.gz
        wget 'http://ann.turkunlp.org:8088/ajax.cgi?action=downloadCollection&collection=%2Fstring-relation-corpus%2Fphysical-interaction-dbs-full-texts-01%2F&include_conf=1&protocol=1' -O physical-interaction-dbs-full-texts-01.tar.gz
        wget 'http://ann.turkunlp.org:8088/ajax.cgi?action=downloadCollection&collection=%2Fstring-relation-corpus%2Fphysical-interaction-dbs-full-texts-02%2F&include_conf=1&protocol=1' -O physical-interaction-dbs-full-texts-02.tar.gz
        wget 'http://ann.turkunlp.org:8088/ajax.cgi?action=downloadCollection&collection=%2Fstring-relation-corpus%2Fregulatory-interactions-reactome-abstracts-01%2F&include_conf=1&protocol=1' -O regulatory-interactions-reactome-abstracts-01.tar.gz
        wget 'http://ann.turkunlp.org:8088/ajax.cgi?action=downloadCollection&collection=%2Fstring-relation-corpus%2Fexhaustive-ptm-corpus-for-re%2F&include_conf=1&protocol=1' -O  exhaustive-ptm-corpus-for-re.tar.gz
        wget 'http://ann.turkunlp.org:8088/ajax.cgi?action=downloadCollection&collection=%2Fstring-relation-corpus%2Fptm-triaged-abstracts-01%2F&include_conf=1&protocol=1' -O  ptm-triaged-abstracts-01.tar.gz
        """



rule untar_directories:
    input:
        expand("{dir}.tar.gz", dir=values)
    output:
        directory("{dir}")
    shell:
        """
        for i in *.tar.gz; do
            tar -xzf $i
        done
        rm *.tar.gz
        """


rule remove_relationships:
    input:
        expand("{dir}/*", dir=values)
    output:
        touch("{dir}-removed-relationships.flag")
    shell:
        """
        for dir in {{input.dir}}; do
            find "$dir" -type f -name "*.ann" -exec perl -ni -e 'print unless /^#/ or /^R/ or /^T(?!.*Complex)/' {{}} +
        done
        """

rule create_all_files_directory:
    input:
        expand("{dir}/*", dir=values),
        "CoNECo_train-ids-with-dirs.txt",
        "CoNECo_dev-ids-with-dirs.txt",
        "CoNECo_test-ids-with-dirs.txt"
    output:
        directory("all-files")
    shell:
        """
        mkdir all-files
        for dir in {{input[0]}}; do
            cp $dir/* all-files/
        done
        """

# Define the arr list
arr = ["train", "dev", "test"]

rule split_directories:
    input:
        "all-files",
        expand("CoNECo_{subset}-ids.txt", subset=arr)  # Use expand to generate all combinations
    output:
        directory("splits")
    shell:
        """
        for i in {{input.subset}}; do
            subset=$(basename $i | cut -d'-' -f2 | cut -d'.' -f1)
            mkdir -p splits/${subset}-set
            cut -f2 $i > splits/${subset}-set/$(basename $i)
            awk '{{print $0 ".ann"; print $0 ".txt"}}' $i > tmp && mv tmp $i
            rsync -a all-files --files-from=$i splits/${subset}-set
        done
        """

rule tar_split_directories:
    input:
        "splits"
    output:
        directory("splits-tarred")
    shell:
        """
        for subset in {{arr}}; do
            mkdir -p splits-tarred
            tar -czf ${subset}-set.tar.gz ${subset}-set
            mv ${subset}-set.tar.gz splits-tarred/
        done
        """

rule tar_splitted_directories:
    input:
        "splits-tarred"
    output:
        directory("CoNECo")
    shell:
        """
        cd splits
        for i in {" ".join(arr)}; do
            tar -czf ${i}-set.tar.gz ${i}-set
        done
        for i in {" ".join(arr)}; do
            rm -rf ${i}-set
        done
        cd ..
        mkdir -p CoNECo
        cp -r splits *.conf CoNECo
        tar -czf CoNECo-corpus.tar.gz CoNECo
        """
